### ISSUE TITLE
[PE-D][Tester E] Overwrite Incorrect Behaviour

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#126]
## Steps to reproduce

Attempt to overwrite a person with another person(follow the screenshot). Overwrite person 2 with person 1 e.g. `overwrite 2 n/... ...`.

## Expected

Success message shows, corresponding person is replaced.

## Actual

![Screenshot 2024-04-05 165413.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/e00ff41f-f92b-4083-a611-bac37a88f88d.png)

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/c65a9b5f-57f6-4b5b-9fb0-fdf725a38a18.png)

When I try to overwrite person 15 with 14, the command is successful but there were no changes in the GUI. When I exited and came back again there was still no change.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: xiaorui-ui/ped#5

**Comment by kervyntan** [comment]
Closed as issue is same as #153
