### ISSUE TITLE
[PE-D][Tester B] Duplicate should not exist

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-2/tp#128]
Does not make alot of sense to have a duplicate user. Is there a reason we want to have duplicate users? Would this not allow for creating mass duplicates? This seems like it could be confusing and error prone
![Screenshot 2024-04-05 at 4.57.09 PM.png](https://raw.githubusercontent.com/Ryo-Seah/ped/main/files/859779c3-f46c-44ed-9b13-62d1c7c6b187.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Ryo-Seah/ped#6

**Comment by kervyntan** [comment]
Hi @Ryo-Seah, thanks for spotting this bug and highlighting to my team and I. After further investigation, this is linked to a bug that was also pointed out by another member that was linked to our Add command being able to add a contact with an identical name. This duplicate command was actually created to tackle this said loophole in the original project. I hope this addresses your concern and appreciate you spotting this bug out for us.
