### ISSUE TITLE
[PE-D][Tester E] Editing the person doesnt change anything

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#132]
## Steps to reproduce

Choose a person with a nonempty tag. Edit another person to match the person without the tag.

## Expected

An error message saying the same person is already in the person list.

## Actual

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/e3fece6c-b43f-4a1e-a2df-98c41da54d46.png)

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/5a99f60f-0da2-4ca7-8ba7-45559c244885.png)

When I change person 14 to be indentical to person 15, it says the person is changed, but in reality nothing happened. In my opinion, you should change the notion of equality to not take tags into account.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xiaorui-ui/ped#6

**Comment by kervyntan** [comment]
Bug resolved via another separate bug fix to the Add Command
