### ISSUE TITLE
[PE-D][Tester E] Editing doesnt reflect changes

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-2/tp#136]
## Steps to reproduce

I'm not exactly sure, this only happens sometimes

## Expected

Name should change in the GUI

## Actual

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/1037b412-4bf7-46ac-b7dd-9759dad1e187.png)

Editing the name to 132 doesn't change the name in GUI. The previous command was "edit 14 n/132" or "edit 15 n/132"

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: xiaorui-ui/ped#8

**Comment by lynnetteeee** [comment]
Tested out, editing name to 132 almost immediately changes the name in the GUI. Most likely a slip up by tester.
