### ISSUE TITLE
[PE-D][Tester D] Missing space in addByStep GUI message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#143]
> ... clipboard!Type...

Should be

>... clipboard! Type...

![image.png](https://raw.githubusercontent.com/ongzhili/ped/main/files/f589a6b6-b927-470d-aba9-a5cba674954f.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ongzhili/ped#9

**Comment by smolegz** [comment]
Solved

**Comment by smolegz** [comment]
![image](https://github.com/AY2324S2-CS2103T-T12-2/tp/assets/65162027/6baa3a30-5394-467e-aa0e-764b9e418c56)
