### ISSUE TITLE
[PE-D][Tester E] Addbystep GUI Oddities

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-2/tp#144]
## Steps to reproduce

Open up a new GUI window by typing `addbystep`

## Expected

After finishing the steps, the new user should be automatically added for the user

## Actual

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/bbea475e-63b2-496b-9c88-3868deae5517.png)

1. Finishing the prescribed steps doesn't add the contact to the GUI. In my opinion the GUI should do it for you, instead of you copying which is an extra step.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: xiaorui-ui/ped#10

**Comment by AidenLYT** [comment]
`the current behavior inconveniences the user but there is a way to work around it`

The command explicitly stated for user to enter `cp` and paste it manually into the prompt. User guide also guided users about this command.
