### ISSUE TITLE
[PE-D][Tester E] Adding a person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#151]
## Steps to reproduce

Add a person whose name has numeric values. e.g. `add n/123 p/999 a/road e/123@mail`

## Expected

An error message appears, telling me the name should be alphabetic.

## Actual

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/b4a00a02-e9fe-4d00-b2f0-340c064d00d5.png)

Name can be added as normal

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xiaorui-ui/ped#13

**Comment by RunjiaChen** [comment]
Not a bug, as stated under Qn 5
