### ISSUE TITLE
[PE-D][Tester A] Typo in overwrite section of UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#154]
Overwrites and existing contact instead of overwrites *an* existing contact. Second part of the sentence is phrased slightly weirdly :/ maybe try `*assuming there is already a contact with an identical identity in the Address Book`

![image.png](https://raw.githubusercontent.com/0nesheep/ped/main/files/0cb59929-162d-4832-8b74-36366df15ad4.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: 0nesheep/ped#10

**Comment by AidenLYT** [comment]
![image](https://github.com/AY2324S2-CS2103T-T12-2/tp/assets/110450637/89004c77-2048-4b69-ae54-7e8724233c39)

Edited the sentence structure
