### ISSUE TITLE
[PE-D][Tester E] Name should not be case sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-2/tp#158]
![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/2d91ffa4-8721-4857-8557-e79fa1cd9677.png)

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/f24ba178-317d-4502-9420-3060c450d384.png)

One would expect "John" and "john" to be treated as the same name. In that case, the duplicate command should succeed.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xiaorui-ui/ped#16

**Comment by RunjiaChen** [comment]
Counted as duplicate, will be examined later

**Comment by kervyntan** [comment]
Will specify in UG that "John" and"john" should be treated as different names, since bug resolved for AddCommand allows addition of these 2 separate names
