### ISSUE TITLE
[PE-D][Tester E] Fields should allow for spaces in between

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-2/tp#162]
## Steps to reproduce

Add a person whose phone number has spaces: e.g. `add n/john p/999 999e/john@mail a/road`

## Expected

Accepts the phone number and trims the space. Spaces are mostly for readability.

## Actual

It returns an error message(see below)

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/9e34056c-b4a1-4589-9cf9-b6571adbd9e9.png)

![image.png](https://raw.githubusercontent.com/xiaorui-ui/ped/main/files/bb2c21f3-4806-4639-9c0e-f7294fa7731e.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xiaorui-ui/ped#19

**Comment by RunjiaChen** [comment]
Dont change, as it falls under Q1 
https://nus-cs2103-ay2324s2.github.io/website/admin/tp-w12.html#2-start-fixing-ped-bugs-before-the-tutorial

**Comment by AidenLYT** [comment]
![image](https://github.com/AY2324S2-CS2103T-T12-2/tp/assets/110450637/2059819d-dacd-415e-b6a8-17f47e4c80e2)

The restriction in the input field is documented in the user guide
