### ISSUE TITLE
!!EVERYBODY!! Update DG by wk10 

### ISSUE THREAD

**Issue by lynnetteeee** [AY2324S2-CS2103T-T12-2/tp#69]
Update the Developer Guide as follows:

- Each member should describe the implementation of at least one enhancement she has added (or planning to add).
- Expected length: 1+ page per person
- The description can contain things such as
1. How the feature is implemented (or is going to be implemented).
2. Why it is implemented that way.
3. Alternatives considered.

**Comment by smolegz** [comment]
Good job everyone! Will proceed to close this issue.
